version: '3.4'
services:
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - veildb-network

  frontend:
    command: 'bash -c "yarn install && yarn dev"'
    ports:
      - ${FRONTEND_PORT:-3000}:3000