version: '3.4'
services:
  php:
    working_dir: /var/www
    build:
      context: docker
      dockerfile: Dockerfile
    networks:
      - app-network
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      PHP_IDE_CONFIG: serverName=docker
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      #DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}&charset=${POSTGRES_CHARSET:-utf8}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      DATABASE_URL: mysql://root:12345@database:3306/app?serverVersion=8&charset=utf8mb4
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - "./:/var/www"
      - ./docker/php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  nginx:
    image: nginx:alpine
    depends_on:
      - php
    tty: true
    ports:
      - ${NGINX_PORT}:80
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  database:
    image: mysql:8.0.22
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    networks:
      - app-network
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#  phpmyadmin:
#    depends_on:
#      - database
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - '${PHPMYADMIN_PORT}:80'
#    environment:
#      PMA_HOST: database
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#    networks:
#      - app-network
#  database:
#    image: postgres:${POSTGRES_VERSION:-15}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    ports:
#      - "5432:5432"
#    networks:
#      - app-network
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
